// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgQK3XyHNH9kP9SwWI3Kx5pBiyymzz09k',
    appId: '1:391011061311:android:ba6814df55901da15bb28a',
    messagingSenderId: '391011061311',
    projectId: 'compumovil-bf4d1',
    storageBucket: 'compumovil-bf4d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTuxffIN6HVjYLQ6GHkhzNumBbIIzNOPM',
    appId: '1:391011061311:ios:d6060e832afec93f5bb28a',
    messagingSenderId: '391011061311',
    projectId: 'compumovil-bf4d1',
    storageBucket: 'compumovil-bf4d1.firebasestorage.app',
    androidClientId: '391011061311-ckda31hnt0r3mi25pqa557mf1v97ukbk.apps.googleusercontent.com',
    iosClientId: '391011061311-n29snminueaqis405cdart60sjlvslao.apps.googleusercontent.com',
    iosBundleId: 'com.utem.appClient',
  );
}
